# Generated by Django 3.2.13 on 2022-06-30 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('xpaccount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_set', to=settings.AUTH_USER_MODEL, verbose_name='Assessor'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='xp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_set', to='xpaccount.xpaccount', verbose_name='Conta XP'),
        ),
        migrations.AddField(
            model_name='relatoriomensal',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatoriomensal_set', to=settings.AUTH_USER_MODEL, verbose_name='Assessor'),
        ),
        migrations.AddField(
            model_name='relatoriomensal',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_set', to=settings.AUTH_USER_MODEL, verbose_name='Master'),
        ),
        migrations.AddField(
            model_name='relatoriomensal',
            name='revenue',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='relatorio_mensal', to='reports.revenue', verbose_name='Receita'),
        ),
        migrations.AddField(
            model_name='relatoriomensal',
            name='xp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatoriomensal_set', to='xpaccount.xpaccount', verbose_name='Conta XP'),
        ),
        migrations.AddField(
            model_name='positivador',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positivador_set', to=settings.AUTH_USER_MODEL, verbose_name='Assessor'),
        ),
        migrations.AddField(
            model_name='positivador',
            name='xp_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positivador_set', to='xpaccount.xpaccount', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='csvrevenue',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='csvrevenue_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csvrevenue',
            name='revenue',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='csv_revenue', to='reports.revenue', verbose_name='Receita'),
        ),
        migrations.AddField(
            model_name='csvrevenue',
            name='xp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='csvrevenue_set', to='xpaccount.xpaccount'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captacao_set', to=settings.AUTH_USER_MODEL, verbose_name='Assessor'),
        ),
        migrations.AddField(
            model_name='captacao',
            name='xp_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captacao_set', to='xpaccount.xpaccount', verbose_name='Conta XP'),
        ),
    ]
